### ISSUE TITLE
Road to supported Installation - round 2

### ISSUE THREAD

**Issue by cirocosta** [concourse/hush-house#38]
Hey,

At the moment, `hush-house` has pretty much feature parity with
[`wings`][wings-post], which was accomplished through our first iteration (see
https://github.com/concourse/hush-house/issues/27).

<br />

In this second iteration, we plan to refine it more, aiming at two goals:

- making `hush-house` compelling for internal teams, and
- making it more maintainable.

<br />

To achieve those, here are some of the steps to get us there:

- [ ] Add panel descriptions - https://github.com/concourse/hush-house/issues/15
- [ ] Allow teams to leverage credential management
  - [ ] Verify if we can use k8s secrets as team credential management - https://github.com/concourse/hush-house/issues/40
    - if so, go with it
    - otherwise, evaluate [`Vault`][vault]
- [ ] Deploy `hush-house` from main Concourse pipeline - https://github.com/concourse/hush-house/issues/28
- [x] Alert based on SLIs - https://github.com/concourse/hush-house/issues/39
- [x] document k8s credential management - https://github.com/concourse/docs/issues/96
- [x] Remove `hush-house.concourse-ci.org` domain from `concourse-ci-org` zone
  - https://github.com/concourse/hush-house/commit/7735302c7db173edfe1c109213a119cf5993f3a9
- [x] Improve documentation about the `terraform` definitions
  - https://github.com/concourse/hush-house/commit/3d1da46e3fb8bbe6598c24212e5e8327e6cf4ed2
- [x] fix terraform deprecation warnings - https://github.com/concourse/hush-house/issues/44
- [x] get rid of AlertManager - https://github.com/concourse/hush-house/issues/43

<br />

---

Not included in this iteration, but soon to be:

- Allow the provisioning of team-specific workers
  - some teams might have the desired of having their own team-specific workers;
    what if we could just manage their workers for them?
- Continuously deploy `metrics`
- Continuously `terraform apply`
  - whenever the terraform scripts are updated.

Thanks!

[wings-post]: https://medium.com/concourse-ci/earning-our-wings-a0c307fa73e6
[vault]: https://www.vaultproject.io/
